# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='classified',
            field=models.BooleanField(default=False),
        ),
    ]
