# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 14:01
from __future__ import unicode_literals

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='text',
            field=redactor.fields.RedactorField(default='', verbose_name='Text'),
        ),
    ]
