# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 16:11
from __future__ import unicode_literals

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_page_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=redactor.fields.RedactorField(default='', verbose_name='Text'),
        ),
    ]
